extern crate cbindgen;

use std::env;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    // This build a header file for the module
    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_language(cbindgen::Language::C)
        .with_header("/* Generated by cbindgen: do not edit by hand */")
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("include/foxdbg.h");
}
