/* Generated by cbindgen: do not edit by hand */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Initializes the debugging system and starts the server thread.
 */
void foxdbg_init(void);

/**
 * Polls for received data callbacks. This should be called periodically in your application's main loop to process incoming messages.
 */
void foxdbg_update(void);

/**
 * Shuts down the server and cleans up resources.
 */
void foxdbg_shutdown(void);

/**
 * Creates a new channel (topic) to publish data to Foxglove. It returns a channel ID for
 * use with other functions.
 */
int foxdbg_add_channel(const char *topic_name, int channel_type, int target_hz);

/**
 * Creates a channel to receive data from Foxglove (for simple types like float, integer, boolean).
 */
int foxdbg_add_rx_channel(const char *topic_name, int channel_type);

/**
 * Writes a data payload to a specified channel.
 */
void foxdbg_write_channel(const char *topic_name, const void *data, uintptr_t size);

/**
 * Writes metadata for a channel, used for types like images to specify dimensions.
 */
void foxdbg_write_channel_info(int channel_id, const void *data, uintptr_t size);
